name: E2E Regression

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to run?
        required: true
        options:
          - electron
          - chrome
          - firefox
      environment:
        type: choice
        description: Which environment to run?
        required: true
        options:
          - qa
          - staging
          - prod
      grep:
        description: 'Optional tag or pattern (e.g. @smoke)'
        required: false
        default: ''
  schedule:
    - cron: '0 8 * * *'

jobs:
  cypress:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run runHead -- --env env='${{github.event.inputs.environment}}',grepTags=${{ github.event.inputs.grep }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/reports/html/**
            cypress/screenshots/**
            cypress/videos/**
            cypress/reports/*.json
          retention-days: 30
