name: E2E Regression

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      grep:
        description: 'Optional tag or pattern (e.g. @smoke)'
        required: false
        default: ''
  schedule:
    - cron: '0 8 * * *'

jobs:
  cypress:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node: [20]
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          command: npm run runProd

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-${{ matrix.browser }}-artifacts
          path: |
            cypress/reports/html/**
            cypress/screenshots/**
            cypress/videos/**
            cypress/reports/*.json
          retention-days: 30
